# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      environment:
        description: environment
        default: ''
        required: true 
        type: choice
        options:
          - TEST_CMS_3
          - TEST_CMS_2
          - DEV
      Email:
        description: receiver email
        default: ''
        required: true
      
      
jobs:
  utilization_report:
    environment: ${{inputs.environment}}
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
    - name: Setup latest NPM
      run: npm install -g npm@latest
    - name: Setup dependencies
      run: npm install
    - name: run node script
      env:
        password: ${{ secrets.PASSWORD}}
        user: ${{ secrets.USER}}
        assetPort: ${{ secrets.ASSET_PORT}}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY}}
        MongoURI: ${{ secrets.MongoURI}}
      run: node cmsUtilization.js ${{inputs.environment}} ${{inputs.email}}
